resolver: lts-14.27

packages:
- .

extra-deps:
- slick-1.0.1.1
- reanimate-svg-0.9.8.0
#-reanimte-0.2.0.2 <- This works with nix-shell --command shake
- git: https://github.com/Lemmih/reanimate
  commit: 8c7f4f34b75c1c410ce4b951b4410ae9a2b26031

nix:
  enable: false
  pure: false
  packages: [libffi, zlib]
